//! Integration with the C++ core running on an ESP32: the test app in
//! cpp/test_app, with its UART1 at the serial device `TETHER_UART`, either
//! QEMU's pty or a USB-UART adapter wired to a board (`TETHER_UART_BAUD` sets
//! the rate; 0 for a pty). `make -C cpp qemu-test` starts QEMU and runs these;
//! they're ignored otherwise.
//!
//! The device runs the C++ server with the Greeter service of
//! cpp/test_app/greeter.fbs, generated by tether-gen for C++, and a Rust client
//! calls it, generated for Rust from the same schema: the handshake,
//! retransmits, both cores' framing, calls, channels with credit and
//! cancellation, with the C++ one built for and running on the target.

extern crate alloc;

mod generated;

use std::io::{ErrorKind, Read, Write};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex, PoisonError, mpsc};
use std::time::{Duration, Instant, SystemTime};

use generated::greeter_generated::test::{BlobT, CountT, EmptyT, Number};
use generated::greeter_rpc::test::greeter;
use tether::{Message, MethodId, RawChannel, Status, Table};
use tether_core::client::{Client, SharedClient};
use tether_core::link::{LinkConfig, LinkState};

type Channel<T> = tether::Channel<tether_core::client::Channel, T>;

/// The most channels the device serves at once.
const MAX_STREAMS: usize = 2;

/// The device serves one test at a time.
static DEVICE: Mutex<()> = Mutex::new(());

/// The Rust end of a link to the device. A thread reads the port all the
/// time: QEMU blocks on writing to a full pty, so a reader that also writes
/// can deadlock with it.
struct Device {
    port: Box<dyn serialport::SerialPort>,
    received: mpsc::Receiver<Vec<u8>>,
    stop: Arc<AtomicBool>,
    reader: Option<std::thread::JoinHandle<()>>,
    client: SharedClient,
    start: Instant,
}

impl Device {
    /// Opens the port (retrying while QEMU starts) and links with a new boot
    /// id. The device sees a reboot, starts a new link of its own, and links
    /// with this one.
    fn connect() -> Self {
        let path = std::env::var("TETHER_UART").expect("TETHER_UART: the device's serial port");
        // The test app's rate. 0 is for a pty, which has none (and on macOS
        // fails when given one).
        let baud = std::env::var("TETHER_UART_BAUD").map_or(921_600, |b| b.parse().unwrap());
        let deadline = Instant::now() + Duration::from_secs(60);
        let port = loop {
            match serialport::new(&path, baud).timeout(Duration::from_millis(10)).open() {
                Ok(port) => break port,
                Err(e) if Instant::now() < deadline => {
                    eprintln!("waiting for {path}: {e}");
                    std::thread::sleep(Duration::from_millis(500));
                }
                Err(e) => panic!("can't open {path}: {e}"),
            }
        };
        let (tx, received) = mpsc::channel();
        let stop = Arc::new(AtomicBool::new(false));
        let reader = {
            let mut port = port.try_clone().unwrap();
            let stop = stop.clone();
            std::thread::spawn(move || {
                let mut buf = [0; 512];
                while !stop.load(Ordering::Relaxed) {
                    match port.read(&mut buf) {
                        Ok(n) => tx.send(buf[..n].to_vec()).unwrap(),
                        Err(e) if matches!(e.kind(), ErrorKind::TimedOut) => {}
                        Err(e) => panic!("{e}"),
                    }
                }
            })
        };
        let nanos = SystemTime::now().duration_since(SystemTime::UNIX_EPOCH).unwrap().as_nanos();
        let client = SharedClient::new(Client::new(nanos as u32 | 1, LinkConfig::default()));
        let mut device =
            Self { port, received, stop, reader: Some(reader), client, start: Instant::now() };
        device.pump_until(Duration::from_secs(60), |d| {
            matches!(d.client.borrow().link_state(), LinkState::Linked { .. })
        });
        device
    }

    fn now(&self) -> u64 {
        self.start.elapsed().as_millis() as u64
    }

    /// One round of the client's I/O: writes what's due, then reads what arrived.
    fn pump_once(&mut self) {
        let (state, stats) = (self.client.borrow().link_state(), self.client.borrow().link_stats());
        assert!(!state.is_terminal(), "link {state:?}, {stats:?}");
        loop {
            let wire = self.client.borrow_mut().poll_transmit(self.now());
            let Some(wire) = wire else { break };
            self.write(&wire);
        }
        // Everything that arrived, before sending again: writes can block
        // while QEMU drains the pty, and acks mustn't wait behind them.
        match self.received.recv_timeout(Duration::from_millis(5)) {
            Ok(bytes) => self.client.borrow_mut().receive(&bytes),
            Err(mpsc::RecvTimeoutError::Timeout) => {}
            Err(e) => panic!("the reader stopped: {e}"),
        }
        while let Ok(bytes) = self.received.try_recv() {
            self.client.borrow_mut().receive(&bytes);
        }
    }

    /// Runs the client until `done` holds.
    fn pump_until(&mut self, timeout: Duration, mut done: impl FnMut(&mut Self) -> bool) {
        let deadline = Instant::now() + timeout;
        while !done(self) {
            let (state, stats) =
                (self.client.borrow().link_state(), self.client.borrow().link_stats());
            assert!(Instant::now() < deadline, "timed out; link {state:?}, {stats:?}");
            self.pump_once();
        }
    }

    /// Runs the client for `duration`, for things to happen on the device.
    fn run_for(&mut self, duration: Duration) {
        let end = Instant::now() + duration;
        while Instant::now() < end {
            self.pump_once();
        }
    }

    /// The generated client.
    fn greeter(&self) -> greeter::Client<&SharedClient> {
        greeter::Client(&self.client)
    }

    /// A typed call, waited for.
    fn wait<T: Table>(
        &mut self,
        mut call: tether::Call<tether_core::client::Call, T>,
    ) -> Result<Message<T>, Status> {
        let mut result = None;
        self.pump_until(Duration::from_secs(10), |_| {
            result = call.try_result();
            result.is_some()
        });
        result.unwrap()
    }

    /// What a typed channel delivers, until it ends.
    fn drain<T: Table>(
        &mut self,
        channel: &mut Channel<T>,
    ) -> (Vec<Message<T>>, Result<(), Status>) {
        let mut items = Vec::new();
        let mut end = None;
        self.pump_until(Duration::from_secs(30), |_| {
            items.extend(std::iter::from_fn(|| channel.try_recv()));
            end = channel.end();
            end.is_some()
        });
        (items, end.unwrap())
    }

    /// The bytes the device echoes back.
    fn echo(&mut self, bytes: &[u8]) -> Vec<u8> {
        let call = self.greeter().echo(&BlobT { data: Some(bytes.to_vec()) });
        let message = self.wait(call).unwrap();
        message.get().data().expect("the vector").bytes().to_vec()
    }

    /// The device's counters: calls started, and calls cancelled.
    fn stats(&mut self) -> (u32, u32) {
        let call = self.greeter().stats(&EmptyT::default());
        let message = self.wait(call).unwrap();
        (message.get().calls(), message.get().cancelled())
    }

    /// The numbers a Countdown or Burst channel delivers, and how it ended.
    fn numbers(&mut self, channel: &mut Channel<Number<'static>>) -> (Vec<u8>, Result<(), Status>) {
        let (items, end) = self.drain(channel);
        (items.iter().map(|m| m.get().value()).collect(), end)
    }

    /// A call by id with any bytes for a request, waited for.
    fn raw_call(&mut self, method: MethodId, request: &[u8]) -> Result<Vec<u8>, Status> {
        let call = self.client.borrow_mut().call(method, request.to_vec(), 5_000);
        let mut result = None;
        self.pump_until(Duration::from_secs(10), |_| {
            result = call.try_result();
            result.is_some()
        });
        result.unwrap()
    }

    /// How a channel opened by id with any bytes for a request ends.
    fn raw_open(&mut self, method: MethodId, request: &[u8]) -> Result<(), Status> {
        let channel = self.client.borrow_mut().open(method, request.to_vec(), 1);
        let mut end = None;
        self.pump_until(Duration::from_secs(10), |_| {
            end = channel.end();
            end.is_some()
        });
        end.unwrap()
    }

    /// Writes bytes straight to the port, around the link.
    fn inject(&mut self, bytes: &[u8]) {
        self.write(bytes);
    }

    /// Writes all of `bytes`, waiting while the device doesn't read (it
    /// doesn't while it boots).
    fn write(&mut self, mut bytes: &[u8]) {
        let deadline = Instant::now() + Duration::from_secs(20);
        while !bytes.is_empty() {
            assert!(Instant::now() < deadline, "the device isn't reading");
            match self.port.write(bytes) {
                Ok(n) => bytes = &bytes[n..],
                Err(e) if matches!(e.kind(), ErrorKind::TimedOut) => {}
                Err(e) => panic!("{e}"),
            }
        }
    }
}

impl Drop for Device {
    fn drop(&mut self) {
        // Stop reading, so the next test's connection gets every byte.
        self.stop.store(true, Ordering::Relaxed);
        if let Some(reader) = self.reader.take() {
            let _ = reader.join();
        }
    }
}

fn golden_frames() -> Vec<serde_json::Value> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../golden/frames.json");
    serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap()
}

fn unhex(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
#[ignore = "needs the test app in QEMU; run `make -C cpp qemu-test`"]
fn links_with_the_device() {
    let _device = DEVICE.lock().unwrap_or_else(PoisonError::into_inner);
    let device = Device::connect();
    let LinkState::Linked { peer_boot_id } = device.client.borrow().link_state() else {
        unreachable!()
    };
    assert_ne!(peer_boot_id, 0);
}

#[test]
#[ignore = "needs the test app in QEMU; run `make -C cpp qemu-test`"]
fn echoes_every_padding() {
    let _device = DEVICE.lock().unwrap_or_else(PoisonError::into_inner);
    let mut device = Device::connect();
    // Zeros for COBS, every length modulo 8 for the padding, and runs past one
    // COBS block, up to the device's largest payload.
    for len in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 16, 17, 253, 254, 255, 256, 511, 900] {
        let request: Vec<u8> = (0..len).map(|i| (i * 31 % 251) as u8).collect();
        assert_eq!(device.echo(&request), request, "{len} bytes");
    }
}

#[test]
#[ignore = "needs the test app in QEMU; run `make -C cpp qemu-test`"]
fn recovers_from_bad_frames_and_line_noise() {
    let _device = DEVICE.lock().unwrap_or_else(PoisonError::into_inner);
    let mut device = Device::connect();
    let bad: Vec<_> = (golden_frames().iter())
        .filter(|g| g.get("error").is_some())
        .map(|g| unhex(g["wire"].as_str().unwrap()))
        .collect();
    assert!(!bad.is_empty());
    for (i, wire) in bad.iter().enumerate() {
        // A bad frame, then noise without a delimiter: the next frame, ours or
        // an ack, is lost, and the link retransmits.
        device.inject(wire);
        device.inject(&[0x55, 0xAA, 0x13]);
        let request = vec![i as u8, 1, 2, 3];
        assert_eq!(device.echo(&request), request, "after {i}");
    }
    // Some frame was lost, in one direction or the other.
    let stats = device.client.borrow().link_stats();
    assert!(stats.retransmits + stats.duplicates > 0, "the noise cost no frame: {stats:?}");
}

#[test]
#[ignore = "needs the test app in QEMU; run `make -C cpp qemu-test`"]
fn streams_with_credit() {
    let _device = DEVICE.lock().unwrap_or_else(PoisonError::into_inner);
    let mut device = Device::connect();
    // Far more items than the channel holds: the device waits for the Credits
    // frames it verifies, as the client frees slots.
    let mut channel = device.greeter().countdown(&CountT { n: 200 }, 4);
    let (numbers, end) = device.numbers(&mut channel);
    assert_eq!(end, Ok(()));
    assert_eq!(numbers, (1..=200).rev().collect::<Vec<u8>>());
    let stats = device.client.borrow().stats();
    assert_eq!((stats.overruns, stats.stale_items), (0, 0));
}

#[test]
#[ignore = "needs the test app in QEMU; run `make -C cpp qemu-test`"]
fn latest_value_skips_what_the_client_cant_take() {
    let _device = DEVICE.lock().unwrap_or_else(PoisonError::into_inner);
    let mut device = Device::connect();
    // The device sets 1..=100 as fast as it can, to a channel with room for
    // one. The first goes out; the client is slower than the rest, so only the
    // newest is kept for when it frees the slot.
    let mut channel = device.greeter().burst(&CountT { n: 100 }, 1);
    let mut numbers = Vec::new();
    device.pump_until(Duration::from_secs(10), |_| {
        numbers.extend(std::iter::from_fn(|| channel.try_recv()).map(|m| m.get().value()));
        numbers.len() >= 2
    });
    assert_eq!(numbers, [1, 100]);
    // And that's all there is: it doesn't repeat, and the channel stays open.
    device.run_for(Duration::from_millis(200));
    assert!(channel.try_recv().is_none());
    assert_eq!(channel.end(), None);
}

#[test]
#[ignore = "needs the test app in QEMU; run `make -C cpp qemu-test`"]
fn an_empty_stream_ends_at_once() {
    let _device = DEVICE.lock().unwrap_or_else(PoisonError::into_inner);
    let mut device = Device::connect();
    let mut channel = device.greeter().countdown(&CountT { n: 0 }, 1);
    assert_eq!(device.numbers(&mut channel), (vec![], Ok(())));
}

#[test]
#[ignore = "needs the test app in QEMU; run `make -C cpp qemu-test`"]
fn the_router_answers_what_isnt_served() {
    let _device = DEVICE.lock().unwrap_or_else(PoisonError::into_inner);
    let mut device = Device::connect();
    // An unknown method, a service that isn't there, and the wrong kind of
    // call, both ways.
    for method in [MethodId::new(0, 9), MethodId::new(1, 0), greeter::COUNTDOWN] {
        assert_eq!(device.raw_call(method, &[]), Err(Status::Unimplemented), "{method:?}");
    }
    for method in [MethodId::new(0, 9), MethodId::new(1, 0), greeter::ECHO] {
        assert_eq!(device.raw_open(method, &[]), Err(Status::Unimplemented), "{method:?}");
    }
}

#[test]
#[ignore = "needs the test app in QEMU; run `make -C cpp qemu-test`"]
fn the_generated_service_answers_what_it_cant_read() {
    let _device = DEVICE.lock().unwrap_or_else(PoisonError::into_inner);
    let mut device = Device::connect();
    // Not flatbuffers of the request's table.
    for request in [vec![], vec![1, 2], vec![0xFF; 16]] {
        assert_eq!(
            device.raw_call(greeter::ECHO, &request),
            Err(Status::InvalidArgument),
            "{request:?}"
        );
        assert_eq!(
            device.raw_open(greeter::COUNTDOWN, &request),
            Err(Status::InvalidArgument),
            "{request:?}"
        );
    }
}

#[test]
#[ignore = "needs the test app in QEMU; run `make -C cpp qemu-test`"]
fn limits_the_open_channels() {
    let _device = DEVICE.lock().unwrap_or_else(PoisonError::into_inner);
    let mut device = Device::connect();
    // Each waits for credit after its first item, and so stays open.
    let open: Vec<_> = (0..MAX_STREAMS)
        .map(|_| device.greeter().countdown(&CountT { n: 255 }, 1))
        .collect();
    let mut rejected = device.greeter().countdown(&CountT { n: 255 }, 1);
    let (numbers, end) = device.numbers(&mut rejected);
    assert_eq!((numbers.len(), end), (0, Err(Status::ResourceExhausted)));
    assert!(open.iter().all(|c| c.end().is_none()));

    // Dropping cancels them on the device, which frees the room.
    drop(open);
    device.run_for(Duration::from_millis(200));
    // The rejected channel never reached the service, which counts the others
    // and this call.
    assert_eq!(device.stats(), (MAX_STREAMS as u32 + 1, MAX_STREAMS as u32));
    let mut channel = device.greeter().countdown(&CountT { n: 1 }, 1);
    assert_eq!(device.numbers(&mut channel), (vec![1], Ok(())));
}

#[test]
#[ignore = "needs the test app in QEMU; run `make -C cpp qemu-test`"]
fn dropping_a_call_cancels_it_on_the_device() {
    let _device = DEVICE.lock().unwrap_or_else(PoisonError::into_inner);
    let mut device = Device::connect();
    let mut channel = device.greeter().countdown(&CountT { n: 255 }, 2);
    device.pump_until(Duration::from_secs(10), |_| channel.try_recv().is_some());
    drop(channel);
    device.run_for(Duration::from_millis(200));
    // The channel's open, and this call.
    assert_eq!(device.stats(), (2, 1));
}
