// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod common {

    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_STATUS: i8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_STATUS: i8 = 16;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_STATUS: [Status; 17] = [
        Status::OK,
        Status::CANCELLED,
        Status::UNKNOWN,
        Status::INVALID_ARGUMENT,
        Status::DEADLINE_EXCEEDED,
        Status::NOT_FOUND,
        Status::ALREADY_EXISTS,
        Status::PERMISSION_DENIED,
        Status::RESOURCE_EXHAUSTED,
        Status::FAILED_PRECONDITION,
        Status::ABORTED,
        Status::OUT_OF_RANGE,
        Status::UNIMPLEMENTED,
        Status::INTERNAL,
        Status::UNAVAILABLE,
        Status::DATA_LOSS,
        Status::UNAUTHENTICATED,
    ];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct Status(pub i8);
    #[allow(non_upper_case_globals)]
    impl Status {
        pub const OK: Self = Self(0);
        pub const CANCELLED: Self = Self(1);
        pub const UNKNOWN: Self = Self(2);
        pub const INVALID_ARGUMENT: Self = Self(3);
        pub const DEADLINE_EXCEEDED: Self = Self(4);
        pub const NOT_FOUND: Self = Self(5);
        pub const ALREADY_EXISTS: Self = Self(6);
        pub const PERMISSION_DENIED: Self = Self(7);
        pub const RESOURCE_EXHAUSTED: Self = Self(8);
        pub const FAILED_PRECONDITION: Self = Self(9);
        pub const ABORTED: Self = Self(10);
        pub const OUT_OF_RANGE: Self = Self(11);
        pub const UNIMPLEMENTED: Self = Self(12);
        pub const INTERNAL: Self = Self(13);
        pub const UNAVAILABLE: Self = Self(14);
        pub const DATA_LOSS: Self = Self(15);
        pub const UNAUTHENTICATED: Self = Self(16);

        pub const ENUM_MIN: i8 = 0;
        pub const ENUM_MAX: i8 = 16;
        pub const ENUM_VALUES: &'static [Self] = &[
            Self::OK,
            Self::CANCELLED,
            Self::UNKNOWN,
            Self::INVALID_ARGUMENT,
            Self::DEADLINE_EXCEEDED,
            Self::NOT_FOUND,
            Self::ALREADY_EXISTS,
            Self::PERMISSION_DENIED,
            Self::RESOURCE_EXHAUSTED,
            Self::FAILED_PRECONDITION,
            Self::ABORTED,
            Self::OUT_OF_RANGE,
            Self::UNIMPLEMENTED,
            Self::INTERNAL,
            Self::UNAVAILABLE,
            Self::DATA_LOSS,
            Self::UNAUTHENTICATED,
        ];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::OK => Some("OK"),
                Self::CANCELLED => Some("CANCELLED"),
                Self::UNKNOWN => Some("UNKNOWN"),
                Self::INVALID_ARGUMENT => Some("INVALID_ARGUMENT"),
                Self::DEADLINE_EXCEEDED => Some("DEADLINE_EXCEEDED"),
                Self::NOT_FOUND => Some("NOT_FOUND"),
                Self::ALREADY_EXISTS => Some("ALREADY_EXISTS"),
                Self::PERMISSION_DENIED => Some("PERMISSION_DENIED"),
                Self::RESOURCE_EXHAUSTED => Some("RESOURCE_EXHAUSTED"),
                Self::FAILED_PRECONDITION => Some("FAILED_PRECONDITION"),
                Self::ABORTED => Some("ABORTED"),
                Self::OUT_OF_RANGE => Some("OUT_OF_RANGE"),
                Self::UNIMPLEMENTED => Some("UNIMPLEMENTED"),
                Self::INTERNAL => Some("INTERNAL"),
                Self::UNAVAILABLE => Some("UNAVAILABLE"),
                Self::DATA_LOSS => Some("DATA_LOSS"),
                Self::UNAUTHENTICATED => Some("UNAUTHENTICATED"),
                _ => None,
            }
        }
    }
    impl ::core::fmt::Debug for Status {
        fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> ::flatbuffers::Follow<'a> for Status {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
            Self(b)
        }
    }

    impl ::flatbuffers::Push for Status {
        type Output = Status;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
        }
    }

    impl ::flatbuffers::EndianScalar for Status {
        type Scalar = i8;
        #[inline]
        fn to_little_endian(self) -> i8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: i8) -> Self {
            let b = i8::from_le(v);
            Self(b)
        }
    }

    impl<'a> ::flatbuffers::Verifiable for Status {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            i8::run_verifier(v, pos)
        }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for Status {}
} // pub mod Common

#[allow(unused_imports, dead_code)]
pub mod rpc {

    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_KIND: u8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_KIND: u8 = 8;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_KIND: [Kind; 9] = [
        Kind::Hello,
        Kind::Ack,
        Kind::Request,
        Kind::Open,
        Kind::Response,
        Kind::Item,
        Kind::End,
        Kind::Credit,
        Kind::Cancel,
    ];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct Kind(pub u8);
    #[allow(non_upper_case_globals)]
    impl Kind {
        /// Link handshake, unsequenced. Payload: Hello.
        pub const Hello: Self = Self(0);
        /// Link acknowledgement of the sequenced frame numbered `seq`.
        pub const Ack: Self = Self(1);
        /// Client -> server: unary call `call_id` to `method`. Payload: the request.
        pub const Request: Self = Self(2);
        /// Client -> server: open channel `call_id` to `method` with `credit`
        /// initial slots. Payload: the request.
        pub const Open: Self = Self(3);
        /// Server -> client: unary result with `status`, payload when OK.
        pub const Response: Self = Self(4);
        /// Server -> client: one item on channel `call_id`.
        pub const Item: Self = Self(5);
        /// Server -> client: channel `call_id` closed with `status`.
        pub const End: Self = Self(6);
        /// Client -> server: the app consumed `credit` more items of `call_id`.
        pub const Credit: Self = Self(7);
        /// Client -> server: the client dropped `call_id`.
        pub const Cancel: Self = Self(8);

        pub const ENUM_MIN: u8 = 0;
        pub const ENUM_MAX: u8 = 8;
        pub const ENUM_VALUES: &'static [Self] = &[
            Self::Hello,
            Self::Ack,
            Self::Request,
            Self::Open,
            Self::Response,
            Self::Item,
            Self::End,
            Self::Credit,
            Self::Cancel,
        ];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::Hello => Some("Hello"),
                Self::Ack => Some("Ack"),
                Self::Request => Some("Request"),
                Self::Open => Some("Open"),
                Self::Response => Some("Response"),
                Self::Item => Some("Item"),
                Self::End => Some("End"),
                Self::Credit => Some("Credit"),
                Self::Cancel => Some("Cancel"),
                _ => None,
            }
        }
    }
    impl ::core::fmt::Debug for Kind {
        fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> ::flatbuffers::Follow<'a> for Kind {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
            Self(b)
        }
    }

    impl ::flatbuffers::Push for Kind {
        type Output = Kind;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
        }
    }

    impl ::flatbuffers::EndianScalar for Kind {
        type Scalar = u8;
        #[inline]
        fn to_little_endian(self) -> u8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: u8) -> Self {
            let b = u8::from_le(v);
            Self(b)
        }
    }

    impl<'a> ::flatbuffers::Verifiable for Kind {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            u8::run_verifier(v, pos)
        }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for Kind {}
    pub enum HeaderOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct Header<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for Header<'a> {
        type Inner = Header<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
        }
    }

    impl<'a> Header<'a> {
        pub const VT_KIND: ::flatbuffers::VOffsetT = 4;
        pub const VT_SEQ: ::flatbuffers::VOffsetT = 6;
        pub const VT_CALL_ID: ::flatbuffers::VOffsetT = 8;
        pub const VT_METHOD: ::flatbuffers::VOffsetT = 10;
        pub const VT_CREDIT: ::flatbuffers::VOffsetT = 12;
        pub const VT_STATUS: ::flatbuffers::VOffsetT = 14;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            Header { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args HeaderArgs,
        ) -> ::flatbuffers::WIPOffset<Header<'bldr>> {
            let mut builder = HeaderBuilder::new(_fbb);
            builder.add_method(args.method);
            builder.add_call_id(args.call_id);
            builder.add_credit(args.credit);
            builder.add_seq(args.seq);
            builder.add_status(args.status);
            builder.add_kind(args.kind);
            builder.finish()
        }

        #[inline]
        pub fn kind(&self) -> Kind {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<Kind>(Header::VT_KIND, Some(Kind::Hello)).unwrap() }
        }
        /// Link sequence number; 0 for Hello, the acknowledged number for Ack.
        #[inline]
        pub fn seq(&self) -> u16 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u16>(Header::VT_SEQ, Some(0)).unwrap() }
        }
        #[inline]
        pub fn call_id(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(Header::VT_CALL_ID, Some(0)).unwrap() }
        }
        /// fnv1a_32 of the method's full name, e.g. "CoprocessorProto.Wifi/Connect".
        #[inline]
        pub fn method(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(Header::VT_METHOD, Some(0)).unwrap() }
        }
        #[inline]
        pub fn credit(&self) -> u16 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u16>(Header::VT_CREDIT, Some(0)).unwrap() }
        }
        #[inline]
        pub fn status(&self) -> super::common::Status {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<super::common::Status>(
                        Header::VT_STATUS,
                        Some(super::common::Status::OK),
                    )
                    .unwrap()
            }
        }
    }

    impl ::flatbuffers::Verifiable for Header<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<Kind>("kind", Self::VT_KIND, false)?
                .visit_field::<u16>("seq", Self::VT_SEQ, false)?
                .visit_field::<u32>("call_id", Self::VT_CALL_ID, false)?
                .visit_field::<u32>("method", Self::VT_METHOD, false)?
                .visit_field::<u16>("credit", Self::VT_CREDIT, false)?
                .visit_field::<super::common::Status>("status", Self::VT_STATUS, false)?
                .finish();
            Ok(())
        }
    }
    pub struct HeaderArgs {
        pub kind: Kind,
        pub seq: u16,
        pub call_id: u32,
        pub method: u32,
        pub credit: u16,
        pub status: super::common::Status,
    }
    impl<'a> Default for HeaderArgs {
        #[inline]
        fn default() -> Self {
            HeaderArgs {
                kind: Kind::Hello,
                seq: 0,
                call_id: 0,
                method: 0,
                credit: 0,
                status: super::common::Status::OK,
            }
        }
    }

    pub struct HeaderBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> HeaderBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_kind(&mut self, kind: Kind) {
            self.fbb_.push_slot::<Kind>(Header::VT_KIND, kind, Kind::Hello);
        }
        #[inline]
        pub fn add_seq(&mut self, seq: u16) {
            self.fbb_.push_slot::<u16>(Header::VT_SEQ, seq, 0);
        }
        #[inline]
        pub fn add_call_id(&mut self, call_id: u32) {
            self.fbb_.push_slot::<u32>(Header::VT_CALL_ID, call_id, 0);
        }
        #[inline]
        pub fn add_method(&mut self, method: u32) {
            self.fbb_.push_slot::<u32>(Header::VT_METHOD, method, 0);
        }
        #[inline]
        pub fn add_credit(&mut self, credit: u16) {
            self.fbb_.push_slot::<u16>(Header::VT_CREDIT, credit, 0);
        }
        #[inline]
        pub fn add_status(&mut self, status: super::common::Status) {
            self.fbb_.push_slot::<super::common::Status>(
                Header::VT_STATUS,
                status,
                super::common::Status::OK,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> HeaderBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            HeaderBuilder { fbb_: _fbb, start_: start }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<Header<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for Header<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("Header");
            ds.field("kind", &self.kind());
            ds.field("seq", &self.seq());
            ds.field("call_id", &self.call_id());
            ds.field("method", &self.method());
            ds.field("credit", &self.credit());
            ds.field("status", &self.status());
            ds.finish()
        }
    }
    pub enum HelloOffset {}
    #[derive(Copy, Clone, PartialEq)]

    /// Sent until the peer's Hello arrives. A Hello with a different `boot_id`
    /// after that means the peer rebooted.
    pub struct Hello<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for Hello<'a> {
        type Inner = Hello<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
        }
    }

    impl<'a> Hello<'a> {
        pub const VT_BOOT_ID: ::flatbuffers::VOffsetT = 4;
        pub const VT_PEER_BOOT_ID: ::flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            Hello { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args HelloArgs,
        ) -> ::flatbuffers::WIPOffset<Hello<'bldr>> {
            let mut builder = HelloBuilder::new(_fbb);
            builder.add_peer_boot_id(args.peer_boot_id);
            builder.add_boot_id(args.boot_id);
            builder.finish()
        }

        #[inline]
        pub fn boot_id(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(Hello::VT_BOOT_ID, Some(0)).unwrap() }
        }
        /// The peer's boot_id as seen by the sender, 0 if none yet.
        #[inline]
        pub fn peer_boot_id(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(Hello::VT_PEER_BOOT_ID, Some(0)).unwrap() }
        }
    }

    impl ::flatbuffers::Verifiable for Hello<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<u32>("boot_id", Self::VT_BOOT_ID, false)?
                .visit_field::<u32>("peer_boot_id", Self::VT_PEER_BOOT_ID, false)?
                .finish();
            Ok(())
        }
    }
    pub struct HelloArgs {
        pub boot_id: u32,
        pub peer_boot_id: u32,
    }
    impl<'a> Default for HelloArgs {
        #[inline]
        fn default() -> Self {
            HelloArgs { boot_id: 0, peer_boot_id: 0 }
        }
    }

    pub struct HelloBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> HelloBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_boot_id(&mut self, boot_id: u32) {
            self.fbb_.push_slot::<u32>(Hello::VT_BOOT_ID, boot_id, 0);
        }
        #[inline]
        pub fn add_peer_boot_id(&mut self, peer_boot_id: u32) {
            self.fbb_.push_slot::<u32>(Hello::VT_PEER_BOOT_ID, peer_boot_id, 0);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> HelloBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            HelloBuilder { fbb_: _fbb, start_: start }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<Hello<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for Hello<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("Hello");
            ds.field("boot_id", &self.boot_id());
            ds.field("peer_boot_id", &self.peer_boot_id());
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `Header`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_header_unchecked`.
    pub fn root_as_header(buf: &[u8]) -> Result<Header<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root::<Header>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `Header` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_header_unchecked`.
    pub fn size_prefixed_root_as_header(
        buf: &[u8],
    ) -> Result<Header<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root::<Header>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `Header` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_header_unchecked`.
    pub fn root_as_header_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<Header<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root_with_opts::<Header<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `Header` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_header_unchecked`.
    pub fn size_prefixed_root_as_header_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<Header<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root_with_opts::<Header<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a Header and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `Header`.
    pub unsafe fn root_as_header_unchecked(buf: &[u8]) -> Header<'_> {
        unsafe { ::flatbuffers::root_unchecked::<Header>(buf) }
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed Header and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `Header`.
    pub unsafe fn size_prefixed_root_as_header_unchecked(buf: &[u8]) -> Header<'_> {
        unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Header>(buf) }
    }
    #[inline]
    pub fn finish_header_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<Header<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_header_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<Header<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod Rpc
